
SO  = egextra
COMPONENT = cellapp
SRCS =						\
	debug_extra				\
	egextra					\
	egcontroller			\
	speed_extra				\
	speed_controller		\

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/server/egextra,,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/server/common/common.mak

all::

