LIB =	math

SRCS =				\
	boundbox		\
	matrix			\
	planeeq			\
	portal2d		\
	quat			\
	vector2			\
	vector3			\
	vector4			\

ifndef MF_ROOT
export MF_ROOT := $(subst /src/lib/$(LIB),,$(CURDIR))
endif

include $(MF_ROOT)/src/lib/makestuf/stdmake.mak

